- name: docker gpg setup
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    update_cache: yes
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install docker-ce
  apt:
    pkg:
      - docker-ce
      - docker-compose-plugin

- name: add "{{ ansible_user }}" to docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker SDK for Python
  apt:
    pkg:
      - python3
      - python3-pip

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: "docker==6.1.3"

- name: Install docker-compose SDK for Python
  pip:
    name: "docker-compose"
